github:
  default_org: "upserve"
  default_repo: "pos-service"
  mappings:
    "upserve/pos-service": "pos"
    "erebusbat/chezmoi": "cz"

jira:
  domain: "https://upserve.atlassian.net"
  projects:
    - AI
    - UPOS

url:
  domain_mappings:
    lightspeedhq_slack_com: slack
    youtube_com: YouTube
    mail_google_com: GMail
