github:
  default_org: "upserve"
  default_repo: "pos-service"
  mappings:
    "upserve/pos-service": "pos"

jira:
  domain: "https://upserve.atlassian.net"
  projects:
    - AI
    - HQ
    - UPOS
    - SEC

jenkins:
  domain: "https://jenkins.internal.upserve.com"

url:
  domain_mappings:
    lightspeedhq_slack_com: slack
    youtube_com: YouTube
    mail_google_com: GMail
