keybinding:
  files:
    commitChangesWithEditor: <disabled>
customCommands:
  - key: C
    context: files
    command: git commit --verbose
    output: terminal
  - key: '!'
    context: worktrees
    command: cd {{.SelectedWorktree.Path}} && LAZYGIT_SHELL=1 $SHELL
    output: terminal
gui:
  mouseEvents: false
git:
  parseEmoji: true
  pagers:
    - pager: delta --dark --paging=never
